// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASGCCdx2RQjzXHzzVu57s4pQpedqiw_L8',
    appId: '1:1078688879443:web:eecb3d8140779b5dfe87a6',
    messagingSenderId: '1078688879443',
    projectId: 'videoapps-studyoio',
    authDomain: 'videoapps-studyoio.firebaseapp.com',
    storageBucket: 'videoapps-studyoio.appspot.com',
    measurementId: 'G-6E0LTC8940',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZ7V8NRViUQ_2lO1l5B_6HJK3FV8EvUw',
    appId: '1:1078688879443:android:249ddd0c16deb2dcfe87a6',
    messagingSenderId: '1078688879443',
    projectId: 'videoapps-studyoio',
    storageBucket: 'videoapps-studyoio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCessMeewGnDwREThD9arhHrVx456miBKg',
    appId: '1:1078688879443:ios:935c775c64f32abdfe87a6',
    messagingSenderId: '1078688879443',
    projectId: 'videoapps-studyoio',
    storageBucket: 'videoapps-studyoio.appspot.com',
    iosBundleId: 'com.example.intershipTestStudyoio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCessMeewGnDwREThD9arhHrVx456miBKg',
    appId: '1:1078688879443:ios:935c775c64f32abdfe87a6',
    messagingSenderId: '1078688879443',
    projectId: 'videoapps-studyoio',
    storageBucket: 'videoapps-studyoio.appspot.com',
    iosBundleId: 'com.example.intershipTestStudyoio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASGCCdx2RQjzXHzzVu57s4pQpedqiw_L8',
    appId: '1:1078688879443:web:c0037f1952b155aafe87a6',
    messagingSenderId: '1078688879443',
    projectId: 'videoapps-studyoio',
    authDomain: 'videoapps-studyoio.firebaseapp.com',
    storageBucket: 'videoapps-studyoio.appspot.com',
    measurementId: 'G-JVWCG6MXSS',
  );
}
